
USE GD2C2018

-- ESTE SCRIPT ELIMINA TODAS LAS CONSTRAINT DE LA DB

DECLARE @sql NVARCHAR(MAX);
SET @sql = N'';

SELECT @sql = @sql + N'
  ALTER TABLE ' + QUOTENAME(s.name) + N'.'
  + QUOTENAME(t.name) + N' DROP CONSTRAINT '
  + QUOTENAME(c.name) + ';'
FROM sys.objects AS c
INNER JOIN sys.tables AS t
ON c.parent_object_id = t.[object_id]
INNER JOIN sys.schemas AS s 
ON t.[schema_id] = s.[schema_id]
WHERE c.[type] IN ('D','C','F','PK','UQ')
ORDER BY c.[type];

PRINT @sql;
EXEC sys.sp_executesql @sql;


-- ELIMINAR TABLAS

DROP TABLE CAMPUS_ANALYTICA.Canjes;

DROP TABLE CAMPUS_ANALYTICA.Cliente;

DROP TABLE CAMPUS_ANALYTICA.ClienteDireccion;

DROP TABLE CAMPUS_ANALYTICA.Compra;

DROP TABLE CAMPUS_ANALYTICA.Direccion;

DROP TABLE CAMPUS_ANALYTICA.Empresa;

DROP TABLE CAMPUS_ANALYTICA.EmpresaDireccion;

DROP TABLE CAMPUS_ANALYTICA.Facturas;

DROP TABLE CAMPUS_ANALYTICA.Funcionalidad;

DROP TABLE CAMPUS_ANALYTICA.Grados_publicacion;

DROP TABLE CAMPUS_ANALYTICA.Items_factura;

DROP TABLE CAMPUS_ANALYTICA.Premios;

DROP TABLE CAMPUS_ANALYTICA.Publicaciones;

DROP TABLE CAMPUS_ANALYTICA.Rol;

DROP TABLE CAMPUS_ANALYTICA.Rol_Funcionalidad;

DROP TABLE CAMPUS_ANALYTICA.Rubros;

DROP TABLE CAMPUS_ANALYTICA.Tajetas;

DROP TABLE CAMPUS_ANALYTICA.Tipos_publicacion;

DROP TABLE CAMPUS_ANALYTICA.Tipos_usuario;

DROP TABLE CAMPUS_ANALYTICA.Ubicacion;

DROP TABLE CAMPUS_ANALYTICA.Usuario;

DROP TABLE CAMPUS_ANALYTICA.Usuario_Rol;

DROP TABLE CAMPUS_ANALYTICA.TIPO_DOCUMENTO;

DROP TABLE dbo.Logins;

-- End of file.

